#!/bin/bash

advertise_topics=(clock map tf tf_static)

#for i in ${advertise_topics[@]}; do
#  rosrun rocon_flip advertise_hub_publisher.py $i
#done

for i in ${advertise_topics[@]}; do
  rosrun rocon_flip generic_advertiser.py -t $i
done
