#!/bin/bash

namespace=(pioneer1 pioneer2) #pioneer2 pioneer3 pioneer4 pioneer5)
remotes=(aadi1 aadi4) #aadi2 aadi3 aadi4 aadi5)
sub_topics=(/tf move_base/current_goal move_base/local_costmap/costmap move_base/local_costmap/costmap_updates move_base/NavfnROS/plan move_base/TrajectoryPlannerROS/local_plan)
sub_nodes=(rviz)
sub_robot_len=${#namespace[@]}
sub_topic_len=${#sub_topics[@]}

for (( i=0; i<${sub_robot_len}; i++ )); do
  for (( j=0; j<${sub_topic_len}; j++ )); do
    rosrun rocon_flip flip_hub_subscriber.py ${namespace[$i]} ${sub_topics[$j]} ${sub_nodes[0]} ${remotes[$i]}
  done
done
