#!/bin/bash

pull_topics=(clock map tf tf_static)
gate=(Hub_Gateway)
#for i in ${pull_topics[@]}; do
#  rosrun rocon_flip pull_hub_publisher.py $i
#done

for i in ${pull_topics[@]}; do
  rosrun rocon_flip generic_puller.py -g ${gate[0]} -t $i
done
