#!/bin/bash

gate=(aadi1_gateway aadi4_gateway)
gate_len=${#gate[@]}
namespace=(sender)
pub_topics=(original_message)
pub_nodes=(original_msg_publisher)
pub_len=${#pub_topics[@]}

for (( j=0; j<${gate_len}; j++ )); do
  for (( i=0; i<${pub_len}; i++ )); do
    rosrun rocon_flip generic_flip_publisher.py ${gate[$j]} ${namespace[0]} ${pub_topics[$i]} ${pub_nodes[$i]}
  done
done

namespace=(receiver)
sub_topics=(machine_name)
sub_nodes=(original_msg_publisher)
sub_len=${#sub_topics[@]}

for (( j=0; j<${gate_len}; j++ )); do
  for (( i=0; i<${sub_len}; i++ )); do
    rosrun rocon_flip generic_flip_subscriber.py ${gate[$j]} ${namespace[0]} ${sub_topics[$i]} ${sub_nodes[$i]}
  done
done
