#!/bin/bash

#namespace=($ROBOT_NAME)
#sub_topics=(base_scan odom)
#sub_nodes=(amcl move_base)
#sub_len=${#sub_topics[@]}

#for (( i=0; i<${sub_len}; i++ )); do
#  rosrun rocon_flip flip_remote_subscriber.py ${namespace[0]} ${sub_topics[$i]} ${sub_nodes[$i]}
#done

gate=(aadi1_gateway)
namespace=(vostro)
pub_topics=(vostro_message)
pub_nodes=(vostro_publisher)
pub_len=${#pub_topics[@]}

for (( i=0; i<${pub_len}; i++ )); do
  rosrun rocon_flip generic_flip_publisher.py ${gate[0]} ${namespace[0]} ${pub_topics[$i]} ${pub_nodes[$i]}
done

