#!/bin/bash

gate=(Hub_Gateway)
gate_len=${#gate[@]}
pub_topics=($ROBOT_NAME/membership $ROBOT_NAME/delayed)
pub_nodes=(pioneer_traffic pioneer_traffic)
pub_len=${#pub_topics[@]}

for (( j=0; j<${gate_len}; j++ )); do
  for (( i=0; i<${pub_len}; i++ )); do
    rosrun rocon_flip generic_flip_publisher.py -g ${gate[$j]} -t ${pub_topics[$i]} -n ${pub_nodes[$i]}
  done
done
